### PR TITLE
Fix Waffle detection on non-Android

### PR DESCRIPTION
**Pull request by linkmauve**
On a standard ArchLinux with aur/waffle installed, the current FindWaffle.cmake can’t find the library because it is in /usr/include/waffle-1/ instead of directly in /usr/include/ like it is expecting.

Instead of hardcoding this path, I added pkg-config support so it will work wherever the user has Waffle installed, as long as they provide a .pc file.

### CODE REVIEW

**Comment by jrfonseca** [comment]
I'm OK with the patch, but I believe that noawadays Waffle ships .cmake files so this can be done even easier.

I don't recall the exact details, but I believe that piglit's CMakeLists was update to import waffle like that at one point.

**Comment by jrfonseca** [comment]
This didn't work for me -- I had to rename `PkgConfig_FOUND` to `PKG_CONFIG_FOUND`

**Comment by linkmauve** [comment]
Here is a new version using the FindWaffle.cmake script provided by Waffle itself.

**Comment by jrfonseca** [comment]
> Here is a new version using the FindWaffle.cmake script provided by Waffle itself.

@linkmauve Thanks. I already pushed this, plus a few more changes.  Could you please rebase?

**Pull request closed without merging**
