### PR TITLE
cmake: enable LTO

### PR DESCRIPTION
**Pull request by okias**
```
444M	build
360M	build-lto
```

TBD:
 - test replay performance (seems to be good)
 - fix GCC / Clang warnings

### CODE REVIEW

**Comment by jrfonseca** [comment]
It looks like backtrace btest fails with LTO.  

You might be able to avoid the issue by disabling the `INTERPROCEDURAL_OPTIMIZATION` property on the `btest` target, and possibly backtrace library itself.

**Comment by jrfonseca** [comment]
What I suggested is just incrementally different, not radically different, as `CMAKE_INTERPROCEDURAL_OPTIMIZATION` is used to initalize `INTERPROCEDURAL_OPTIMIZATION` properties.

To be clear, what I'm suggesting is `set (CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)`  globally (as you already do), then `set_target_properties(foo PROPERTIES INTERPROCEDURAL_OPTIMIZATION FALSE)` where and only if needed.

**Comment by okias** [comment]
Had to switch the LTO off for whole libbacktrace, since disabling per target (btest/stest) didn't helped. Anyway the results is good (in terms of size).

**Comment by jrfonseca** [comment]
https://github.com/apitrace/apitrace/pull/866/commits/db3c2c5ec5bf68b8362776154cfd940dc912434d looks good.

https://github.com/apitrace/apitrace/pull/866/commits/7b8d60c339f312e992eab03f56a506a97e1a22d3 surprised me.  IIUC, from https://developers.redhat.com/blog/2017/02/22/memory-error-detection-using-gcc description `-Walloc-size-larger-than=` warning relies on static code analysis.  I'd prefer an `assert`, but likely the warning would persist on non-debug builds, so I suppose clamping is indeed the simplest thing to do.  I think we should use `PTRDIFF_MAX` instead of `INT_MAX`, to avoid unnecessarily limits on 64-bits builds.  Otherwise that too looks good.

**Comment by okias** [comment]
Thanks, updated to the `PTRDIFF_MAX`, good catch :)

**Comment by okias** [comment]
hmm, the `ubuntu32` job is broken :(

**Comment by jrfonseca** [comment]
It's not your fault.  GitHub broken the ubuntu base image for 32bit packages somehow.  If you rebase, it should pick up master change to use docker for this job, and it should start working,

**Comment by okias** [comment]
Thanks, rebased.

**Pull request merged**
