### PR TITLE
Use Python3_EXECUTABLE in cmake.

### PR DESCRIPTION
**Pull request by jdashg**

### CODE REVIEW

**Comment by jdashg** [comment]
This fixed my build issues on MacOS.
Previously, I was getting "permission denied: glproc.py" and other errors.

**Comment by jrfonseca** [comment]
Hmm it seems to cause problems with older CMake (see travis).  Do you know CMake version this Python3 module works reliably?

**Comment by jdashg** [comment]
Looks like CMake 3.12.

**Comment by jrfonseca** [comment]
Thanks. I pushed an updated version of your change, which keeps the old behavior for older CMake.

Hopefully this gets the best of both worlds.

**Pull request closed without merging**
