### PR TITLE
Retrace on Android

### PR DESCRIPTION
**Pull request by bog-dan-ro**

### CODE REVIEW

**Comment by jrfonseca** [comment]
A few comments:

* You rebased on top of Qt5 branch. This hasn't merged yet, as I'm having troubles with Qt5 and MinGW cross-compilation.   Is Qt5 a dependency for this?

* You added support to build with Gradle besides CMake.  I'm afraid I can't afford to maintain two build systems.  Furthermore most of the apitrace development happens on other platforms, so  the odds would be that Gradle would be broken most out of the time.

* Please add copyright headers for new `*.[ch]pp` files. (`common/os_memory.cpp` is missing)

Otherwise looks OK. You don't happen to have a screenshot of the GUI running on Android?

**Comment by bog-dan-ro** [comment]
> You rebased on top of Qt5 branch. This hasn't merged yet, as I'm having troubles with Qt5 and MinGW cross-compilation. Is Qt5 a dependency for this?

Well, Qt4 is quite unmaintained, It "might" work also with Qt4 though.


> You added support to build with Gradle besides CMake. I'm afraid I can't afford to maintain two build systems. Furthermore most of the apitrace development happens on other platforms, so the odds would be that Gradle would be broken most out of the time.

Gradle is used only to build the Android APK, is not used to build the .so library. You don't have to change anything in the gradle project files :). We just need to make sure cmake will compile the android_retrace and installs it in the right place, before it starts gradle.
Though, I added a few .pro/.pri (qmake) files that I needed to compile, run & debug the project on Android using QtCreator. Those files are not needed and if you don't like them I can remove them from this patch and  keep them only in my repo.


> Please add copyright headers for new *.[ch]pp files. (common/os_memory.cpp is missing)

The new .cpp/.h files which don't have an explicit copyright header have the same copyright as the rest of the source files.

> Otherwise looks OK. 
Thanks!


> You don't happen to have a screenshot of the GUI running on Android?

The GUI still runs on your Desktop, on Android it runs only the retrace application. Though it is possible to port also the GUI on Android, but it will need some GUI changes to make it touch friendly (most probably we'll need to rewrite it using QuickControls which are touch friendly.

**Comment by bog-dan-ro** [comment]
>  (common/os_memory.cpp is missing)

There is no  os_memory.cpp, I add the implementation to  os_posixy.cpp, because I didn't wanted to add a .cpp file only for 2 functions ...

**Comment by bog-dan-ro** [comment]
> This hasn't merged yet, as I'm having troubles with Qt5 and MinGW cross-compilation

I tried to coss-compile qt5 myself and it worked just fine.
I cloned qtbase, checkout 5.4 branch and I used "./configure -xplatform win32-g++ -device-option CROSS_COMPILE=i686-w64-mingw32- -static -developer-build -no-warnings-are-errors"  to coss-compile it.

**Comment by oscarbg** [comment]
Hi,
this is very interesting.. one question..
I have Nvidia Shield tablet with full OpenGL 4.5 support and would like to know if also OGL desktop profile traces are expected to work on this tablet with your traces.. i.e. EGL context creation in eglretrace handles setting EGL_RENDERABLE_TYPE to either OpenGL_ES_2 or OpenGL depending on the trace?
thanks..

**Comment by bog-dan-ro** [comment]
I don't think you'll be able to retrace non-egl traces, because the retrace depends on (links against) EGL, GLES[1,2,3]. This is the reason why I choose to limit the Android usage in the GUI to EGL traces.

**Comment by bog-dan-ro** [comment]
@jrfonseca please let me know if you prefer me to sqash/split some of the patches.

**Comment by bog-dan-ro** [comment]
Squashed related patches & rebase on top of apitrace:master

**Comment by bog-dan-ro** [comment]
If you want to know more about how these patches work, I wrote an article about it http://www.kdab.com/fun-android/  (Chapter III has the interesting part for you).

**Comment by jrfonseca** [comment]
> If you want to know more about how these patches work, I wrote an article about it http://www.kdab.com/fun-android/ (Chapter III has the interesting part for you). 

Thanks. That indeed helped alot. Very neat.

Could you please:

- rebase on top of master once more (there are conflicts due to the per-call thumbnail support)

- squash "Android: Implement getVsize and getRss" and "Move getVsize and getRss() to os_posix.cpp" commits together (via `git rebase -i`)

- prefix commits with "os:", "retrace:", "gui:" depending 

Also, although I don't use Android myself, I want to be able to build it so I can ensure at least that builds don't get broken.  However, trying to build your branch, as you documented, fails with:

    Linking CXX shared library ../../../libs/armeabi-v7a/libretrace.so
    CMakeFiles/retrace.dir/glws_egl_android.cpp.o:/home/jfonseca/projects/apitrace/retrace/glws_egl_android.cpp:function glws::readParamsAndStartTrace(): error: undefined reference to 'std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11u>)'
    CMakeFiles/retrace.dir/glws_egl_android.cpp.o:/home/jfonseca/projects/apitrace/retrace/glws_egl_android.cpp:function glws::readParamsAndStartTrace(): error: undefined reference to 'std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
    CMakeFiles/retrace.dir/glws_egl_android.cpp.o:/home/jfonseca/projects/apitrace/retrace/glws_egl_android.cpp:function glws::readParamsAndStartTrace(): error: undefined reference to 'std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
    CMakeFiles/retrace.dir/glws_egl_android.cpp.o:/home/jfonseca/projects/apitrace/retrace/glws_egl_android.cpp:function glws::readParamsAndStartTrace(): error: undefined reference to 'std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
    CMakeFiles/retrace.dir/glws_egl_android.cpp.o:/home/jfonseca/projects/apitrace/retrace/glws_egl_android.cpp:function glws::readParamsAndStartTrace(): error: undefined reference to 'std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator->()'
    CMakeFiles/retrace.dir/glws_egl_android.cpp.o:/home/jfonseca/projects/apitrace/retrace/glws_egl_android.cpp:function glws::readParamsAndStartTrace(): error: undefined reference to 'std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    retrace/CMakeFiles/retrace.dir/build.make:96: recipe for target '../../libs/armeabi-v7a/libretrace.so' failed
    make[2]: *** [../../libs/armeabi-v7a/libretrace.so] Error 1

Do you know what I might be doing wrong?

**Comment by bog-dan-ro** [comment]
Strange, it works just fine on my side https://paste.kde.org/pnmfwt3qa 
Can you please make sure you are using the latest NDK? It looks like it doesn't picking up the right sdc++ lib ... Make sure you have  "-DANDROID_STL=gnustl_shared" to cmake params!

If it still doesn't work then I'll need more info:
 * I need to know what's your NDK & SDK versions
 * Your cmake params
 * run make with VERBOSE=1 env var set. *e.g. VERBOSE=1 make -j10 retraceAPK
ping me on #necessitas channel on freenode (my nick is bog_dan_ro) or send them by mail.

Anyway, to make it easy for everybody I added a new commit with retrace APK. Feel free to drop it if you don't like it :).

**Comment by bog-dan-ro** [comment]
Please don't merge them yet. I forgot to test the GUI part

**Comment by bog-dan-ro** [comment]
Fixed the GUI.

**Comment by jrfonseca** [comment]
> Can you please make sure you are using the latest NDK?

Indeed upgrading to the latest NDK fixed the issue. Thanks.

**Comment by bog-dan-ro** [comment]
Updated the GUI one more time :)

**Comment by bog-dan-ro** [comment]
Be verbose when pulling/pushing files from/top device.

**Comment by bog-dan-ro** [comment]
rebased

**Comment by jrfonseca** [comment]
Finally merged this!

I took the liberty of squashing things and tidying up white-space. I also tweaked indentation of glws_egl_android to match glws_egl_xlib , and to facilitate keeping both in sync (until the common core is refactored out somehow.)

Let me know if f1baf3782aa58215623ff5001290539a26392e6a broke something.

> I added a few .pro/.pri (qmake) files that I needed to compile, run & debug the project on Android using QtCreator. Those files are not needed and if you don't like them I can remove them from this patch and keep them only in my repo.

I remove them.  BTW, not sure if it meets your needs, but QtCreator can open CMakeLists.txt directly.

**Pull request closed without merging**
