### PR TITLE
Add envvar FLUSH_EVERY_MS.

### PR DESCRIPTION
**Pull request by kdashg**
If present, FLUSH_EVERY_MS forces apitrace to flush trace files at
regular intervals.

### CODE REVIEW

**Comment by jdashg** [comment]
In particular, when tracing (multiprocess) Firefox, background process traces don't seem to flush to disk properly.

**Comment by jrfonseca** [comment]
I agree this is a sensible thing to do. In fact, it probably makes sense to do it by default.

But this needs to be done in a way it doesn't at least break other OSes build.  And I'm afraid C++11 threading primitives are not quite to a point we can use them directly.  Please see the threading abstractions in `lib/os/os_thread.hpp`.

**Comment by jdashg** [comment]
Seems to compile fine after removing those includes to rely on os_thread.hpp.
PTAL!

**Comment by chealy** [comment]
I tested this change as I was facing similar issues with my env.  Change works as described.  It would be good to see this code merged.

Tested-by: Chris Healy <cphealy@gmail.com>

**Pull request merged**
