### PR TITLE
glretrace: use samples value recorded in trace to set MSAA samples

### PR DESCRIPTION
**Pull request by gerddie**
Check the calls that configure the framebuffer format and use the
requested samples value unless this value was set from the command
line.

WIP: currently calling the framebuffer config twice with different samples values will result in ignoring the second value if the first one was != 1. 

Related: #690 

@jrfonseca could you skim over it to see whether this makes any sense?

### CODE REVIEW

**Comment by jrfonseca** [comment]
> @jrfonseca could you skim over it to see whether this makes any sense?

@gerddie, yeah, looks the right direction.

Ideally we'd book-keep visual information like `samples` and `doubleBuffer` and use it on a per-drawable basis, instead of `retrace::` globals but this change is definitely a step step forward.  We can tackle that seperately.

Subsequently, it would be good to have some tests too.  I really need to find the time to integrate https://github.com/apitrace/apitrace-tests into apitrace/tests, so the tests are easier to run.

**Comment by gerddie** [comment]
I've updated the MR to store the sampled on a per FBConfig basis and query the value when creating the context. It seems to work for glretrace, with eglretrace I get the right samples value, but the output doesn't look like MSAA is applied, for wgl I couldn't run any tests.

**Comment by jrfonseca** [comment]
> I've updated the MR to store the sampled on a per FBConfig basis and query the value when creating the context. It seems to work for glretrace, with eglretrace I get the right samples value, but the output doesn't look like MSAA is applied, for wgl I couldn't run any tests.

Looks great.  

glXChooseFBConfig is not sufficient.  Take for example GLFW3, it doesn't use .  Instead it uses glXGetFBConfigs followed by glXGetFBConfigAttrib, and then chooses manually the config.  So for this to work, glretrace should also interpret calls like

    glXGetFBConfigAttrib(dpy = ..., config = foo, attribute = GLX_SAMPLES, value = &4) 

and use this information to populate `fbconfig_map[foo] = 4`.

One can modify https://github.com/apitrace/apitrace-tests/blob/master/apps/gl/tri.cpp to use MSAA to test this.  In fact, I think it would be a good idea on its own right to have a MSAA test.

That said, don't feel you need to nail every corner case before commit -- as long as we're doing forward progress and cause no regressions, partial improvements are great IMO.

**Comment by gerddie** [comment]
I've added the check for glXGetFBConfigAttrib and fixed an issue when no sample count was given.

**Comment by jrfonseca** [comment]
> I've added the check for glXGetFBConfigAttrib and fixed an issue when no sample count was given.

Looks great.  Thanks!

Regarding your outstanding WIP item:
> WIP: currently calling the framebuffer config twice with different samples values will result in ignoring the second value if the first one was != 1.

Can you elaborate the issue? 

I think that even without it this seems a step forward.  As long as it doesn't cause obvious errors crashes with existing traces I'm OK with commiting this.  And we can deal with any issues detected with existing traces after commiting.

**Comment by gerddie** [comment]
I think the thing with the framebuffer config called twice with different sample values is not relevant, i.e. if I understand it correctly, different samples values will also result in different framebuffer configs. 

There was another issue I noted when I tried to implement the tests: sometimes glXMakeCurrent also creates the drawable,and it was using the default profile, therefore all the work with passing the samples value around was done in vain. I've added another commit (the first commit of the PR) to use the context profile  if available when getDrawable creates a new drawable. This fixed up things nicely. 

I've added a test: https://github.com/apitrace/apitrace-tests/pull/8

**Comment by jrfonseca** [comment]
Thanks!

**Pull request merged**
