### PR TITLE
retrace: Add option to pass a query result check threshold

### PR DESCRIPTION
**Pull request by gerddie**
In order to reduce the noise when comparing recorded query values
to evaluated ones while retracing add an option to be able to
specify a threshold for the result difference.
With a threshold > 0 " --query-handling check" will be enabled too.

Related: #715

Signed-off-by: Gert Wollny <gert.wollny@collabora.com>

### CODE REVIEW

**Comment by jrfonseca** [comment]
Some builds are failing with `error: no member named 'setPlaceholderText' in 'QComboBox'`  Either this method is too old or too new?

**Comment by jrfonseca** [comment]
Oh, it's not your fault!  It seems that GitHub Actions migrated to 20.04 and this triggered troubles.  I'm looking into it...

**Comment by jrfonseca** [comment]
I've fixed the master builds, but it turned out to be something completely different.  The `setPlaceholderText` seems introduced by this change.

**Comment by gerddie** [comment]
> I've fixed the master builds, but it turned out to be something completely different. The `setPlaceholderText` seems introduced by this change.

I've removed it and set the initial text instead, It seems to work nicely.-

**Comment by jrfonseca** [comment]
Thanks.

**Pull request merged**
